{"title": "\u201cThe world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\u201d", "author": "Albert Einstein", "tags": ["/tag/change/page/1/", "/tag/deep-thoughts/page/1/", "/tag/thinking/page/1/", "/tag/world/page/1/"]}
{"title": "\u201cIt is our choices, Harry, that show what we truly are, far more than our abilities.\u201d", "author": "J.K. Rowling", "tags": ["/tag/abilities/page/1/", "/tag/choices/page/1/"]}
{"title": "\u201cThere are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.\u201d", "author": "Albert Einstein", "tags": ["/tag/inspirational/page/1/", "/tag/life/page/1/", "/tag/live/page/1/", "/tag/miracle/page/1/", "/tag/miracles/page/1/"]}
{"title": "\u201cThe person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.\u201d", "author": "Jane Austen", "tags": ["/tag/aliteracy/page/1/", "/tag/books/page/1/", "/tag/classic/page/1/", "/tag/humor/page/1/"]}
{"title": "\u201cImperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\u201d", "author": "Marilyn Monroe", "tags": ["/tag/be-yourself/page/1/", "/tag/inspirational/page/1/"]}
{"title": "\u201cTry not to become a man of success. Rather become a man of value.\u201d", "author": "Albert Einstein", "tags": ["/tag/adulthood/page/1/", "/tag/success/page/1/", "/tag/value/page/1/"]}
{"title": "\u201cIt is better to be hated for what you are than to be loved for what you are not.\u201d", "author": "Andr\u00e9 Gide", "tags": ["/tag/life/page/1/", "/tag/love/page/1/"]}
{"title": "\u201cI have not failed. I've just found 10,000 ways that won't work.\u201d", "author": "Thomas A. Edison", "tags": ["/tag/edison/page/1/", "/tag/failure/page/1/", "/tag/inspirational/page/1/", "/tag/paraphrased/page/1/"]}
{"title": "\u201cA woman is like a tea bag; you never know how strong it is until it's in hot water.\u201d", "author": "Eleanor Roosevelt", "tags": ["/tag/misattributed-eleanor-roosevelt/page/1/"]}
{"title": "\u201cA day without sunshine is like, you know, night.\u201d", "author": "Steve Martin", "tags": ["/tag/humor/page/1/", "/tag/obvious/page/1/", "/tag/simile/page/1/"]}
{"title": "\u201cThis life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.\u201d", "author": "Marilyn Monroe", "tags": ["/tag/friends/page/1/", "/tag/heartbreak/page/1/", "/tag/inspirational/page/1/", "/tag/life/page/1/", "/tag/love/page/1/", "/tag/sisters/page/1/"]}
{"title": "\u201cIt takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.\u201d", "author": "J.K. Rowling", "tags": ["/tag/courage/page/1/", "/tag/friends/page/1/"]}
{"title": "\u201cIf you can't explain it to a six year old, you don't understand it yourself.\u201d", "author": "Albert Einstein", "tags": ["/tag/simplicity/page/1/", "/tag/understand/page/1/"]}
{"title": "\u201cYou may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect\u2014you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break\u2014her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.\u201d", "author": "Bob Marley", "tags": ["/tag/love/page/1/"]}
{"title": "\u201cI like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.\u201d", "author": "Dr. Seuss", "tags": ["/tag/fantasy/page/1/"]}
{"title": "\u201cI may not have gone where I intended to go, but I think I have ended up where I needed to be.\u201d", "author": "Douglas Adams", "tags": ["/tag/life/page/1/", "/tag/navigation/page/1/"]}
{"title": "\u201cThe opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.\u201d", "author": "Elie Wiesel", "tags": ["/tag/activism/page/1/", "/tag/apathy/page/1/", "/tag/hate/page/1/", "/tag/indifference/page/1/", "/tag/inspirational/page/1/", "/tag/love/page/1/", "/tag/opposite/page/1/", "/tag/philosophy/page/1/"]}
{"title": "\u201cIt is not a lack of love, but a lack of friendship that makes unhappy marriages.\u201d", "author": "Friedrich Nietzsche", "tags": ["/tag/friendship/page/1/", "/tag/lack-of-friendship/page/1/", "/tag/lack-of-love/page/1/", "/tag/love/page/1/", "/tag/marriage/page/1/", "/tag/unhappy-marriage/page/1/"]}
{"title": "\u201cGood friends, good books, and a sleepy conscience: this is the ideal life.\u201d", "author": "Mark Twain", "tags": ["/tag/books/page/1/", "/tag/contentment/page/1/", "/tag/friends/page/1/", "/tag/friendship/page/1/", "/tag/life/page/1/"]}
{"title": "\u201cLife is what happens to us while we are making other plans.\u201d", "author": "Allen Saunders", "tags": ["/tag/fate/page/1/", "/tag/life/page/1/", "/tag/misattributed-john-lennon/page/1/", "/tag/planning/page/1/", "/tag/plans/page/1/"]}
{"title": "\u201cI love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.\u201d", "author": "Pablo Neruda", "tags": ["/tag/love/page/1/", "/tag/poetry/page/1/"]}
{"title": "\u201cFor every minute you are angry you lose sixty seconds of happiness.\u201d", "author": "Ralph Waldo Emerson", "tags": ["/tag/happiness/page/1/"]}
{"title": "\u201cIf you judge people, you have no time to love them.\u201d", "author": "Mother Teresa", "tags": ["/tag/attributed-no-source/page/1/"]}
{"title": "\u201cAnyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.\u201d", "author": "Garrison Keillor", "tags": ["/tag/humor/page/1/", "/tag/religion/page/1/"]}
{"title": "\u201cBeauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.\u201d", "author": "Jim Henson", "tags": ["/tag/humor/page/1/"]}
{"title": "\u201cToday you are You, that is truer than true. There is no one alive who is Youer than You.\u201d", "author": "Dr. Seuss", "tags": ["/tag/comedy/page/1/", "/tag/life/page/1/", "/tag/yourself/page/1/"]}
{"title": "\u201cIf you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.\u201d", "author": "Albert Einstein", "tags": ["/tag/children/page/1/", "/tag/fairy-tales/page/1/"]}
{"title": "\u201cIt is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all - in which case, you fail by default.\u201d", "author": "J.K. Rowling", "tags": []}
{"title": "\u201cLogic will get you from A to Z; imagination will get you everywhere.\u201d", "author": "Albert Einstein", "tags": ["/tag/imagination/page/1/"]}
{"title": "\u201cOne good thing about music, when it hits you, you feel no pain.\u201d", "author": "Bob Marley", "tags": ["/tag/music/page/1/"]}
{"title": "\u201cThe more that you read, the more things you will know. The more that you learn, the more places you'll go.\u201d", "author": "Dr. Seuss", "tags": ["/tag/learning/page/1/", "/tag/reading/page/1/", "/tag/seuss/page/1/"]}
{"title": "\u201cOf course it is happening inside your head, Harry, but why on earth should that mean that it is not real?\u201d", "author": "J.K. Rowling", "tags": ["/tag/dumbledore/page/1/"]}
{"title": "\u201cThe truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.\u201d", "author": "Bob Marley", "tags": ["/tag/friendship/page/1/"]}
{"title": "\u201cNot all of us can do great things. But we can do small things with great love.\u201d", "author": "Mother Teresa", "tags": ["/tag/misattributed-to-mother-teresa/page/1/", "/tag/paraphrased/page/1/"]}
{"title": "\u201cTo the well-organized mind, death is but the next great adventure.\u201d", "author": "J.K. Rowling", "tags": ["/tag/death/page/1/", "/tag/inspirational/page/1/"]}
{"title": "\u201cAll you need is love. But a little chocolate now and then doesn't hurt.\u201d", "author": "Charles M. Schulz", "tags": ["/tag/chocolate/page/1/", "/tag/food/page/1/", "/tag/humor/page/1/"]}
{"title": "\u201cWe read to know we're not alone.\u201d", "author": "William Nicholson", "tags": ["/tag/misattributed-to-c-s-lewis/page/1/", "/tag/reading/page/1/"]}
{"title": "\u201cAny fool can know. The point is to understand.\u201d", "author": "Albert Einstein", "tags": ["/tag/knowledge/page/1/", "/tag/learning/page/1/", "/tag/understanding/page/1/", "/tag/wisdom/page/1/"]}
{"title": "\u201cI have always imagined that Paradise will be a kind of library.\u201d", "author": "Jorge Luis Borges", "tags": ["/tag/books/page/1/", "/tag/library/page/1/"]}
{"title": "\u201cIt is never too late to be what you might have been.\u201d", "author": "George Eliot", "tags": ["/tag/inspirational/page/1/"]}
{"title": "\u201cA reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.\u201d", "author": "George R.R. Martin", "tags": ["/tag/read/page/1/", "/tag/readers/page/1/", "/tag/reading/page/1/", "/tag/reading-books/page/1/"]}
{"title": "\u201cYou can never get a cup of tea large enough or a book long enough to suit me.\u201d", "author": "C.S. Lewis", "tags": ["/tag/books/page/1/", "/tag/inspirational/page/1/", "/tag/reading/page/1/", "/tag/tea/page/1/"]}
{"title": "\u201cYou believe lies so you eventually learn to trust no one but yourself.\u201d", "author": "Marilyn Monroe", "tags": []}
{"title": "\u201cIf you can make a woman laugh, you can make her do anything.\u201d", "author": "Marilyn Monroe", "tags": ["/tag/girls/page/1/", "/tag/love/page/1/"]}
{"title": "\u201cLife is like riding a bicycle. To keep your balance, you must keep moving.\u201d", "author": "Albert Einstein", "tags": ["/tag/life/page/1/", "/tag/simile/page/1/"]}
{"title": "\u201cThe real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.\u201d", "author": "Marilyn Monroe", "tags": ["/tag/love/page/1/"]}
{"title": "\u201cA wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.\u201d", "author": "Marilyn Monroe", "tags": ["/tag/attributed-no-source/page/1/"]}
{"title": "\u201cOnly in the darkness can you see the stars.\u201d", "author": "Martin Luther King Jr.", "tags": ["/tag/hope/page/1/", "/tag/inspirational/page/1/"]}
{"title": "\u201cIt matters not what someone is born, but what they grow to be.\u201d", "author": "J.K. Rowling", "tags": ["/tag/dumbledore/page/1/"]}
{"title": "\u201cLove does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.\u201d", "author": "James Baldwin", "tags": ["/tag/love/page/1/"]}
{"title": "\u201cThere is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.\u201d", "author": "Jane Austen", "tags": ["/tag/friendship/page/1/", "/tag/love/page/1/"]}
{"title": "\u201cDo one thing every day that scares you.\u201d", "author": "Eleanor Roosevelt", "tags": ["/tag/attributed/page/1/", "/tag/fear/page/1/", "/tag/inspiration/page/1/"]}
{"title": "\u201cI am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.\u201d", "author": "Marilyn Monroe", "tags": ["/tag/attributed-no-source/page/1/"]}
{"title": "\u201cIf I were not a physicist, I would probably be a musician. I often think in music. I live my daydreams in music. I see my life in terms of music.\u201d", "author": "Albert Einstein", "tags": ["/tag/music/page/1/"]}
{"title": "\u201cIf you only read the books that everyone else is reading, you can only think what everyone else is thinking.\u201d", "author": "Haruki Murakami", "tags": ["/tag/books/page/1/", "/tag/thought/page/1/"]}
{"title": "\u201cThe difference between genius and stupidity is: genius has its limits.\u201d", "author": "Alexandre Dumas fils", "tags": ["/tag/misattributed-to-einstein/page/1/"]}
{"title": "\u201cHe's like a drug for you, Bella.\u201d", "author": "Stephenie Meyer", "tags": ["/tag/drug/page/1/", "/tag/romance/page/1/", "/tag/simile/page/1/"]}
{"title": "\u201cThere is no friend as loyal as a book.\u201d", "author": "Ernest Hemingway", "tags": ["/tag/books/page/1/", "/tag/friends/page/1/", "/tag/novelist-quotes/page/1/"]}
{"title": "\u201cWhen one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.\u201d", "author": "Helen Keller", "tags": ["/tag/inspirational/page/1/"]}
{"title": "\u201cLife isn't about finding yourself. Life is about creating yourself.\u201d", "author": "George Bernard Shaw", "tags": ["/tag/inspirational/page/1/", "/tag/life/page/1/", "/tag/yourself/page/1/"]}
{"title": "\u201cThat's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen.\u201d", "author": "Charles Bukowski", "tags": ["/tag/alcohol/page/1/"]}
{"title": "\u201cYou don\u2019t forget the face of the person who was your last hope.\u201d", "author": "Suzanne Collins", "tags": ["/tag/the-hunger-games/page/1/"]}
{"title": "\u201cRemember, we're madly in love, so it's all right to kiss me anytime you feel like it.\u201d", "author": "Suzanne Collins", "tags": ["/tag/humor/page/1/"]}
{"title": "\u201cTo love at all is to be vulnerable. Love anything and your heart will be wrung and possibly broken. If you want to make sure of keeping it intact you must give it to no one, not even an animal. Wrap it carefully round with hobbies and little luxuries; avoid all entanglements. Lock it up safe in the casket or coffin of your selfishness. But in that casket, safe, dark, motionless, airless, it will change. It will not be broken; it will become unbreakable, impenetrable, irredeemable. To love is to be vulnerable.\u201d", "author": "C.S. Lewis", "tags": ["/tag/love/page/1/"]}
{"title": "\u201cNot all those who wander are lost.\u201d", "author": "J.R.R. Tolkien", "tags": ["/tag/bilbo/page/1/", "/tag/journey/page/1/", "/tag/lost/page/1/", "/tag/quest/page/1/", "/tag/travel/page/1/", "/tag/wander/page/1/"]}
{"title": "\u201cDo not pity the dead, Harry. Pity the living, and, above all those who live without love.\u201d", "author": "J.K. Rowling", "tags": ["/tag/live-death-love/page/1/"]}
{"title": "\u201cThere is nothing to writing. All you do is sit down at a typewriter and bleed.\u201d", "author": "Ernest Hemingway", "tags": ["/tag/good/page/1/", "/tag/writing/page/1/"]}
{"title": "\u201cFinish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.\u201d", "author": "Ralph Waldo Emerson", "tags": ["/tag/life/page/1/", "/tag/regrets/page/1/"]}
{"title": "\u201cI have never let my schooling interfere with my education.\u201d", "author": "Mark Twain", "tags": ["/tag/education/page/1/"]}
{"title": "\u201cI have heard there are troubles of more than one kind. Some come from ahead and some come from behind. But I've bought a big bat. I'm all ready you see. Now my troubles are going to have troubles with me!\u201d", "author": "Dr. Seuss", "tags": ["/tag/troubles/page/1/"]}
{"title": "\u201cIf I had a flower for every time I thought of you...I could walk through my garden forever.\u201d", "author": "Alfred Tennyson", "tags": ["/tag/friendship/page/1/", "/tag/love/page/1/"]}
{"title": "\u201cSome people never go crazy. What truly horrible lives they must lead.\u201d", "author": "Charles Bukowski", "tags": ["/tag/humor/page/1/"]}
{"title": "\u201cThe trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.\u201d", "author": "Terry Pratchett", "tags": ["/tag/humor/page/1/", "/tag/open-mind/page/1/", "/tag/thinking/page/1/"]}
{"title": "\u201cThink left and think right and think low and think high. Oh, the thinks you can think up if only you try!\u201d", "author": "Dr. Seuss", "tags": ["/tag/humor/page/1/", "/tag/philosophy/page/1/"]}
{"title": "\u201cWhat really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though.\u201d", "author": "J.D. Salinger", "tags": ["/tag/authors/page/1/", "/tag/books/page/1/", "/tag/literature/page/1/", "/tag/reading/page/1/", "/tag/writing/page/1/"]}
{"title": "\u201cThe reason I talk to myself is because I\u2019m the only one whose answers I accept.\u201d", "author": "George Carlin", "tags": ["/tag/humor/page/1/", "/tag/insanity/page/1/", "/tag/lies/page/1/", "/tag/lying/page/1/", "/tag/self-indulgence/page/1/", "/tag/truth/page/1/"]}
{"title": "\u201cYou may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.\u201d", "author": "John Lennon", "tags": ["/tag/beatles/page/1/", "/tag/connection/page/1/", "/tag/dreamers/page/1/", "/tag/dreaming/page/1/", "/tag/dreams/page/1/", "/tag/hope/page/1/", "/tag/inspirational/page/1/", "/tag/peace/page/1/"]}
{"title": "\u201cI am free of all prejudice. I hate everyone equally. \u201d", "author": "W.C. Fields", "tags": ["/tag/humor/page/1/", "/tag/sinister/page/1/"]}
{"title": "\u201cThe question isn't who is going to let me; it's who is going to stop me.\u201d", "author": "Ayn Rand", "tags": []}
{"title": "\u201c\u2032Classic\u2032 - a book which people praise and don't read.\u201d", "author": "Mark Twain", "tags": ["/tag/books/page/1/", "/tag/classic/page/1/", "/tag/reading/page/1/"]}
{"title": "\u201cAnyone who has never made a mistake has never tried anything new.\u201d", "author": "Albert Einstein", "tags": ["/tag/mistakes/page/1/"]}
{"title": "\u201cA lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.\u201d", "author": "Jane Austen", "tags": ["/tag/humor/page/1/", "/tag/love/page/1/", "/tag/romantic/page/1/", "/tag/women/page/1/"]}
{"title": "\u201cRemember, if the time should come when you have to make a choice between what is right and what is easy, remember what happened to a boy who was good, and kind, and brave, because he strayed across the path of Lord Voldemort. Remember Cedric Diggory.\u201d", "author": "J.K. Rowling", "tags": ["/tag/integrity/page/1/"]}
{"title": "\u201cI declare after all there is no enjoyment like reading! How much sooner one tires of any thing than of a book! -- When I have a house of my own, I shall be miserable if I have not an excellent library.\u201d", "author": "Jane Austen", "tags": ["/tag/books/page/1/", "/tag/library/page/1/", "/tag/reading/page/1/"]}
{"title": "\u201cThere are few people whom I really love, and still fewer of whom I think well. The more I see of the world, the more am I dissatisfied with it; and every day confirms my belief of the inconsistency of all human characters, and of the little dependence that can be placed on the appearance of merit or sense.\u201d", "author": "Jane Austen", "tags": ["/tag/elizabeth-bennet/page/1/", "/tag/jane-austen/page/1/"]}
{"title": "\u201cSome day you will be old enough to start reading fairy tales again.\u201d", "author": "C.S. Lewis", "tags": ["/tag/age/page/1/", "/tag/fairytales/page/1/", "/tag/growing-up/page/1/"]}
{"title": "\u201cWe are not necessarily doubting that God will do the best for us; we are wondering how painful the best will turn out to be.\u201d", "author": "C.S. Lewis", "tags": ["/tag/god/page/1/"]}
{"title": "\u201cThe fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.\u201d", "author": "Mark Twain", "tags": ["/tag/death/page/1/", "/tag/life/page/1/"]}
{"title": "\u201cA lie can travel half way around the world while the truth is putting on its shoes.\u201d", "author": "Mark Twain", "tags": ["/tag/misattributed-mark-twain/page/1/", "/tag/truth/page/1/"]}
{"title": "\u201cI believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.\u201d", "author": "C.S. Lewis", "tags": ["/tag/christianity/page/1/", "/tag/faith/page/1/", "/tag/religion/page/1/", "/tag/sun/page/1/"]}
{"title": "\u201cThe truth.\" Dumbledore sighed. \"It is a beautiful and terrible thing, and should therefore be treated with great caution.\u201d", "author": "J.K. Rowling", "tags": ["/tag/truth/page/1/"]}
{"title": "\u201cI'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.\u201d", "author": "Jimi Hendrix", "tags": ["/tag/death/page/1/", "/tag/life/page/1/"]}
{"title": "\u201cTo die will be an awfully big adventure.\u201d", "author": "J.M. Barrie", "tags": ["/tag/adventure/page/1/", "/tag/love/page/1/"]}
{"title": "\u201cIt takes courage to grow up and become who you really are.\u201d", "author": "E.E. Cummings", "tags": ["/tag/courage/page/1/"]}
{"title": "\u201cBut better to get hurt by the truth than comforted with a lie.\u201d", "author": "Khaled Hosseini", "tags": ["/tag/life/page/1/"]}
{"title": "\u201cYou never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.\u201d", "author": "Harper Lee", "tags": ["/tag/better-life-empathy/page/1/"]}
{"title": "\u201cYou have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.\u201d", "author": "Madeleine L'Engle", "tags": ["/tag/books/page/1/", "/tag/children/page/1/", "/tag/difficult/page/1/", "/tag/grown-ups/page/1/", "/tag/write/page/1/", "/tag/writers/page/1/", "/tag/writing/page/1/"]}
{"title": "\u201cNever tell the truth to people who are not worthy of it.\u201d", "author": "Mark Twain", "tags": ["/tag/truth/page/1/"]}
{"title": "\u201cA person's a person, no matter how small.\u201d", "author": "Dr. Seuss", "tags": ["/tag/inspirational/page/1/"]}
{"title": "\u201c... a mind needs books as a sword needs a whetstone, if it is to keep its edge.\u201d", "author": "George R.R. Martin", "tags": ["/tag/books/page/1/", "/tag/mind/page/1/"]}
