# mysql
spring:
  datasource:
    url: jdbc:mysql://104.224.178.5:3306/admin
    username: admin
    password: master2011

  data:
    mongodb:
      uri: mongodb://test:master2011@104.224.178.5:27017/test


server:
  port: 80